"use client";

import { useEffect, useRef, useState, type FormEvent } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { Icon } from "./Icon";
import LessonWorkspace from "./LessonWorkspace";
import { readSnapshot, saveSnapshot, getLearningBundle, uid } from "../services/demo";
import type { Accent, DemoSnapshot, Lesson, StudyDocument, StudyNote } from "../types";

const navigation = [
  { id: "home", name: "Tổng quan", icon: "home" },
  { id: "library", name: "Bài học của tôi", icon: "book" },
  { id: "tutor", name: "AI Tutor", icon: "sparkles" },
  { id: "flashcards", name: "Flashcard", icon: "cards" },
  { id: "quiz", name: "Luyện tập Quiz", icon: "quiz" },
  { id: "notes", name: "Sổ tay học tập", icon: "note" },
  { id: "progress", name: "Tiến độ học", icon: "chart" },
];
const titles: Record<string,string> = {home:"Không gian học tập",library:"Bài học của tôi",tutor:"Trợ lý học tập",flashcards:"Ôn tập với Flashcard",quiz:"Luyện tập Quiz",notes:"Sổ tay học tập",progress:"Tiến độ của bạn",create:"Tạo bài học",upload:"Thêm tài liệu",settings:"Thông tin bản demo"};
const accentIcon: Record<string,string> = {mint:"chart",lavender:"brain",peach:"book",blue:"grid"};

function withProgress(snapshot:DemoSnapshot):DemoSnapshot {
  return {...snapshot,lessons:snapshot.lessons.map(lesson=>{const cards=getLearningBundle(lesson).flashcards;const reviewed=cards.filter(card=>snapshot.reviews[lesson.id]?.[card.id]).length;const quizDone=(snapshot.results[lesson.id]?.length||0)>0;return {...lesson,progress:Math.round((cards.length?reviewed/cards.length:0)*60+(quizDone?40:0))};})};
}

export default function StudyApp() {
  const router=useRouter(), pathname=usePathname(), params=useSearchParams();
  const page=pathname.split('/')[1] || 'home';
  const [snapshot,setSnapshot]=useState<DemoSnapshot|null>(null);
  const [search,setSearch]=useState('');
  const [topic,setTopic]=useState('all');
  const [toast,setToast]=useState('');
  const [mobileMenu,setMobileMenu]=useState(false);
  const toastTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
  const searchRef=useRef<HTMLInputElement>(null);
  useEffect(()=>{setSnapshot(withProgress(readSnapshot()));},[]);
  useEffect(()=>{setMobileMenu(false);setTopic('all');},[pathname]);
  useEffect(()=>{
    const handler=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();searchRef.current?.focus();}if(e.key==='Escape')setMobileMenu(false);};
    window.addEventListener('keydown',handler);
    return ()=>{window.removeEventListener('keydown',handler);if(toastTimer.current)clearTimeout(toastTimer.current);};
  },[]);
  const change=(next:DemoSnapshot)=>{const updated=withProgress(next);setSnapshot(updated);saveSnapshot(updated);};
  const notify=(text:string)=>{setToast(text);if(toastTimer.current)clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),4500);};
  const navigate=(to:string)=>{setSearch('');router.push(to);};
  const openLesson=(id:string,tab='summary')=>navigate(`/lesson/${id}?tab=${tab}`);
  if(!snapshot)return <div className="boot-screen"><span className="brand-mark"><Icon name="sparkles"/></span><span className="spinner"/>Đang mở không gian học tập…</div>;
  if(page==='login')navigate('/home');
  const lessonId=pathname.split('/')[2];
  const lesson=snapshot.lessons.find(l=>l.id===lessonId);
  const currentNav=page==='lesson'?'library':page;
  const userName=snapshot.user?.name || 'Bạn học';
  const completedReviews=Object.values(snapshot.reviews).reduce((sum,r)=>sum+Object.keys(r).length,0);
  const totalResults=Object.values(snapshot.results).flat();
  const totalDocs=snapshot.lessons.reduce((sum,l)=>sum+l.documents.length,0);
  const average=totalResults.length?Math.round(totalResults.reduce((sum,r)=>sum+r.scorePercentage,0)/totalResults.length):0;
  const topics=Array.from(new Set(snapshot.lessons.map(l=>l.topic)));
  const shownLessons=snapshot.lessons.filter(l=>(topic==='all'||l.topic===topic)&&`${l.title} ${l.topic} ${l.description}`.toLocaleLowerCase('vi').includes(search.toLocaleLowerCase('vi')));
  const filteredBySearch=search.trim().length>0;
  return <div className="app-shell">
    <a href="#main-content" className="skip-link">Đến nội dung chính</a>
    {mobileMenu&&<button className="sidebar-scrim" onClick={()=>setMobileMenu(false)} aria-label="Đóng menu"/>}
    <aside className={`sidebar ${mobileMenu?'is-open':''}`}>
      <button className="brand" onClick={()=>navigate('/home')} aria-label="AI Study Assistant — Trang chủ"><span className="brand-mark"><Icon name="sparkles" size={24}/></span><span><strong>AI Study Assistant</strong><small>AI STUDY ASSISTANT</small></span></button>
      <div className="sidebar-group-label">KHÔNG GIAN CỦA BẠN</div>
      <nav aria-label="Điều hướng chính">{navigation.map(item=><button key={item.id} className={`nav-item ${currentNav===item.id?'active':''}`} aria-current={currentNav===item.id?'page':undefined} onClick={()=>navigate('/'+item.id)}><Icon name={item.icon} size={19}/><span>{item.name}</span>{item.id==='library'&&<span className="nav-count">{snapshot.lessons.length}</span>}{currentNav===item.id&&<span className="nav-dot"/>}</button>)}</nav>
      <div className="sidebar-bottom">
        <div className="sidebar-callout"><div className="callout-stars">✦ <span>✧</span></div><strong>Kiến thức lớn.<br/>Bắt đầu từ bước nhỏ.</strong><p>Thêm một tài liệu, mở ra<br/>một cách học mới.</p><button className="btn btn-primary" onClick={()=>navigate('/upload')}><Icon name="plus" size={16}/>Thêm tài liệu</button></div>
        <button className="nav-item settings-item" onClick={()=>navigate('/settings')}><Icon name="settings" size={18}/>Thông tin demo</button>
        <div className="user-block"><span className="avatar">{userName.slice(0,1).toUpperCase()}</span><div><strong>{userName}</strong><small>Không gian cá nhân</small></div><button className="icon-button" title="Đăng xuất demo" aria-label="Đăng xuất demo" onClick={()=>{change({...snapshot,user:null});navigate('/login');}}><Icon name="logout" size={17}/></button></div>
      </div>
    </aside>
    <div className="main-shell">
      <header className="topbar">
        <div className="breadcrumb"><button className="icon-button mobile-toggle" aria-label="Mở menu" onClick={()=>setMobileMenu(true)}><Icon name="grid"/></button><span>AI Study Assistant</span><Icon name="chevronRight" size={13}/><strong>{page==='lesson'?'Không gian bài học':titles[page]||'Không gian học tập'}</strong></div>
        <div className="topbar-actions"><label className="global-search"><Icon name="search" size={17}/><input ref={searchRef} aria-label="Tìm bài học" placeholder="Tìm bài học…" value={search} onChange={e=>{setSearch(e.target.value);if(!['home','library'].includes(page))router.push('/library');}}/><kbd>⌘ K</kbd></label><span className="demo-pill"><span/>DEMO</span><button className="avatar topbar-avatar" title="Xem thông tin demo" onClick={()=>navigate('/settings')}>{userName.slice(0,1).toUpperCase()}</button></div>
      </header>
      <main id="main-content" className="main-content" tabIndex={-1}>
        {(page==='home'||page==='library'||['tutor','flashcards','quiz'].includes(page))&&<>
          <div className="page-heading"><div><div className="eyebrow">{page==='home'?'MỖI NGÀY, HIỂU THÊM MỘT CHÚT':page==='library'?'THƯ VIỆN CÁ NHÂN':'HỌC CHỦ ĐỘNG, NHỚ LÂU HƠN'}</div><h1>{page==='home'?<>Chào bạn, sẵn sàng học chưa? <span className="greeting-spark">✦</span></>:titles[page]}</h1><p>{page==='home'?'Một nơi để biến tài liệu thành kiến thức của riêng bạn.':page==='library'?'Tất cả bài học và tài liệu, được sắp xếp gọn gàng.':'Chọn một bài học bên dưới để bắt đầu phiên học của bạn.'}</p></div><button className="btn btn-primary" onClick={()=>navigate('/create')}><Icon name="plus" size={18}/>Tạo bài học</button></div>
          {page==='home'&&!filteredBySearch&&<>
            <section className="hero-banner" aria-label="Giới thiệu không gian học"><div className="hero-copy"><span className="hero-kicker"><Icon name="sparkles" size={15}/>HỌC NHẸ NHÀNG. HIỂU SÂU HƠN.</span><h2>Tài liệu của bạn.<br/><em>Cách học thông minh hơn.</em></h2><p>Tóm tắt ý chính, hỏi điều chưa hiểu và ôn lại<br className="desktop-br"/> bằng flashcard — trong một không gian.</p><button className="btn btn-ink" onClick={()=>navigate('/upload')}>Bắt đầu từ tài liệu<Icon name="arrowRight" size={17}/></button><div className="hero-supported">PDF <span>·</span> Hình ảnh <span>·</span> Ghi âm <span>·</span> Ghi chú</div></div><StudyIllustration/></section>
            <div className="stats-row"><Stat icon="book" value={snapshot.lessons.length.toString().padStart(2,'0')} title="Bài học của bạn" sub={`${totalDocs} tài liệu đã thêm`} accent="mint"/><Stat icon="cards" value={completedReviews.toString().padStart(2,'0')} title="Thẻ đã ôn tập" sub="Một bước gần hơn đến ghi nhớ" accent="lavender"/><Stat icon="quiz" value={totalResults.length.toString().padStart(2,'0')} title="Bài Quiz hoàn thành" sub={totalResults.length?`Điểm trung bình ${average}%`:'Sẵn sàng cho lần thử đầu tiên'} accent="peach"/></div>
          </>}
          <div className={`dashboard-grid ${page!=='home'||filteredBySearch?'full-width':''}`}>
            <section className="lessons-section"><div className="section-heading"><div><h2>{page==='home'?'Tiếp tục hành trình học':filteredBySearch?'Kết quả tìm kiếm':'Bài học của bạn'}</h2><span>{shownLessons.length} bài học <span className="small-separator">·</span> Nội dung mẫu để trải nghiệm</span></div>{page==='home'&&<button className="text-button" onClick={()=>navigate('/library')}>Xem tất cả<Icon name="arrowRight" size={15}/></button>}</div>
              {page!=='home'&&<div className="topic-filters" role="group" aria-label="Lọc chủ đề">{['all',...topics].map(t=><button key={t} aria-pressed={topic===t} className={topic===t?'active':''} onClick={()=>setTopic(t)}>{t==='all'?'Tất cả bài học':t}</button>)}</div>}
              <div className="lesson-grid">{shownLessons.map(l=><LessonCard key={l.id} lesson={l} onOpen={()=>openLesson(l.id,page==='tutor'?'chat':page==='flashcards'?'flashcards':page==='quiz'?'quiz':'summary')}/>)}</div>
              {!shownLessons.length&&<div className="empty-state"><Icon name="search" size={32}/><h3>{filteredBySearch?'Chưa tìm thấy bài học':'Bắt đầu bài học đầu tiên'}</h3><p>{filteredBySearch?'Thử một từ khóa khác hoặc tạo bài học mới.':'Thêm tài liệu và xây dựng thư viện học tập của bạn.'}</p><button className="btn btn-secondary" onClick={()=>filteredBySearch?setSearch(''):navigate('/create')}>{filteredBySearch?'Xóa tìm kiếm':'Tạo bài học'}</button></div>}
            </section>
            {page==='home'&&!filteredBySearch&&<aside className="dashboard-aside"><section className="panel daily-plan"><div className="section-heading"><h2>Gợi ý hôm nay</h2><Icon name="calendar" size={18}/></div><p className="muted small">Một phiên học ngắn cũng tạo khác biệt.</p><div className="daily-timeline">{[{time:'10 phút',title:'Ôn lại những ý chính',sub:'Tóm tắt bài học',icon:'book',tab:'summary'},{time:'5 phút',title:'Thử một bộ flashcard',sub:'Củng cố kiến thức',icon:'cards',tab:'flashcards'},{time:'8 phút',title:'Kiểm tra điều đã hiểu',sub:'Quiz theo bài học',icon:'quiz',tab:'quiz'}].map((item,i)=><button key={item.tab} className="timeline-item" onClick={()=>snapshot.lessons[0]?openLesson(snapshot.lessons[0].id,item.tab):navigate('/create')}><span className={`timeline-icon ${['mint','lavender','peach'][i]}`}><Icon name={item.icon} size={17}/></span><span><small>{item.time}</small><strong>{item.title}</strong><em>{item.sub}</em></span><Icon name="chevronRight" size={14}/></button>)}</div><span className="sample-caption">Gợi ý mẫu · không phải lịch nhắc tự động</span></section>
            <section className="tutor-callout"><div className="tutor-orb"><Icon name="sparkles" size={22}/></div><h3>Chưa hiểu một ý?<br/>Cứ hỏi AI Study Assistant.</h3><p>Thử cách giải thích dễ hiểu<br/>từ nội dung bài học mẫu.</p><button className="text-button" onClick={()=>snapshot.lessons[0]?openLesson(snapshot.lessons[0].id,'chat'):navigate('/create')}>Trò chuyện với AI Tutor<Icon name="arrowRight" size={16}/></button><span className="sample-caption">Phản hồi mô phỏng trong bản demo</span></section></aside>}
          </div>
        </>}
        {page==='create'&&<CreateLesson onCreate={(title,description,topic)=>{const lesson:Lesson={id:uid('lesson'),title,description,topic,accent:'mint',createdAt:new Date().toISOString(),progress:0,documents:[]};change({...snapshot,lessons:[lesson,...snapshot.lessons]});notify('Đã tạo bài học và lưu trên trình duyệt.');navigate(`/upload?lesson=${lesson.id}`);}} onCancel={()=>navigate('/library')}/>}
        {page==='upload'&&<UploadPanel snapshot={snapshot} onChange={change} lessonId={params.get('lesson')||undefined} onOpen={openLesson} notify={notify}/>}
        {page==='lesson'&&(lesson?<LessonWorkspace key={lesson.id} lesson={lesson} snapshot={snapshot} onChange={change} onBack={()=>navigate('/library')} onUpload={()=>navigate(`/upload?lesson=${lesson.id}`)} notify={notify} initialTab={(['summary','chat','mindmap','flashcards','quiz','documents'].includes(params.get('tab')||'')?params.get('tab'):'summary') as 'summary'|'chat'|'mindmap'|'flashcards'|'quiz'|'documents'}/>:<div className="empty-state"><Icon name="book" size={38}/><h2>Bài học không còn trong demo</h2><p>Chọn một bài học khác từ thư viện của bạn.</p><button className="btn btn-primary" onClick={()=>navigate('/library')}>Về thư viện</button></div>)}
        {page==='notes'&&<NotesPanel snapshot={snapshot} onChange={change} notify={notify}/>}
        {page==='progress'&&<ProgressPanel snapshot={snapshot} onOpen={openLesson}/>}
        {page==='settings'&&<div className="settings-page"><div className="eyebrow">BẢN TRẢI NGHIỆM FRONTEND</div><h1>Không gian demo của bạn</h1><p className="muted">Các thao tác được lưu trên trình duyệt này.</p><div className="panel settings-card"><span className="badge">Giai đoạn 3 · Demo độc lập</span><h2>Giao diện thật. Nội dung học mẫu.</h2><p>Bạn có thể tạo bài học, chọn tài liệu, viết ghi chú, trò chuyện với Tutor mẫu, lật thẻ và làm Quiz. Tóm tắt, sơ đồ, phản hồi Tutor và kết quả xử lý file là nội dung mô phỏng.</p><p>Demo đang chạy riêng, chưa gọi backend của nhóm. Tài liệu chọn trên máy không được tải lên máy chủ. Chỉ thông tin tên, dung lượng và ghi chú được lưu tại trình duyệt.</p><div className="settings-features">{['Next.js + TypeScript','Giao diện tiếng Việt','Desktop & Mobile','Dữ liệu demo rõ ràng'].map(t=><span key={t}><Icon name="check" size={15}/>{t}</span>)}</div><button className="btn btn-primary" onClick={()=>navigate('/home')}>Tiếp tục trải nghiệm<Icon name="arrowRight" size={17}/></button></div><div className="panel settings-card"><h3>Phạm vi công việc nhóm</h3><p>Phần bàn giao chỉ thuộc frontend. Backend/API, database, AI/RAG, PDF/OCR/STT và logic học thật thuộc các module của thành viên phụ trách.</p></div></div>}
        {!['home','library','tutor','flashcards','quiz','create','upload','lesson','notes','progress','settings'].includes(page)&&<div className="empty-state"><h2>Trang này chưa có trong demo</h2><button className="btn btn-primary" onClick={()=>navigate('/home')}>Về tổng quan</button></div>}
        <footer className="app-footer"><span>✦ AI Study Assistant · Học theo cách của bạn.</span><span>Bản demo FE <span>·</span> Dữ liệu mẫu</span></footer>
      </main>
    </div>
    {toast&&<div className="toast" role="status"><Icon name="check" size={19}/>{toast}<button onClick={()=>setToast('')} aria-label="Đóng thông báo"><Icon name="close" size={15}/></button></div>}
  </div>;
}

function Stat({icon,value,title,sub,accent}:{icon:string;value:string;title:string;sub:string;accent:string}){return <div className="stat-card"><span className={`stat-icon ${accent}`}><Icon name={icon} size={22}/></span><div><strong>{value}</strong><span>{title}</span><small>{sub}</small></div><Icon name="arrowRight" size={17} className="stat-arrow"/></div>;}

function StudyIllustration(){return <div className="study-art" aria-hidden="true"><div className="art-orbit orbit-one"/><div className="art-orbit orbit-two"/><span className="art-spark one">✦</span><span className="art-spark two">✧</span><div className="art-floating art-mini-card"><span className="art-check"><Icon name="check" size={15}/></span><span>Hiểu sâu hơn<small>Từng bài học một</small></span></div><div className="art-book"><div className="book-left"><span className="art-line wide"/><span className="art-line"/><span className="art-line short"/><div className="book-graph"><span/><span/><span/><span/></div><span className="art-line"/></div><div className="book-right"><span className="art-book-icon"><Icon name="sparkles" size={26}/></span><span className="art-line wide"/><span className="art-line"/><span className="art-line short"/><span className="art-line"/></div><div className="book-spine"/></div><div className="art-floating art-note"><Icon name="cards" size={19}/><span>Nhớ lâu hơn</span><span className="tiny-dot"/></div></div>;}

function LessonCard({lesson,onOpen}:{lesson:Lesson;onOpen:()=>void}){return <button className="lesson-card" onClick={onOpen}><div className={`lesson-cover ${lesson.accent}`}><span className="cover-orbit"/><span className="cover-symbol"><Icon name={accentIcon[lesson.accent]} size={29}/></span><span className="cover-label">{lesson.topic}</span><span className="cover-spark">✦</span></div><div className="lesson-card-body"><span className="lesson-topic">{lesson.topic}</span><h3>{lesson.title}</h3><p>{lesson.description}</p><div className="lesson-meta"><span><Icon name="file" size={14}/>{lesson.documents.length} tài liệu</span><span><Icon name="clock" size={14}/>{Math.max(5,lesson.documents.length*6)} phút ôn</span></div><div className="lesson-progress"><span>Hành trình bài học</span><strong>{lesson.progress}%</strong></div><div className="progress-track"><span style={{width:lesson.progress+'%'}}/></div><div className="lesson-card-footer"><span>Tiếp tục học</span><Icon name="arrowRight" size={17}/></div></div></button>;}

function Login({onLogin}:{onLogin:(name:string,email:string)=>void}){
  const [register,setRegister]=useState(false),[error,setError]=useState('');
  const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const data=new FormData(e.currentTarget),email=String(data.get('email')||'').trim(),password=String(data.get('password')||''),name=String(data.get('name')||'').trim();if(password.length<6){setError('Mật khẩu demo cần ít nhất 6 ký tự.');return;}onLogin(name||email.split('@')[0]||'Bạn học',email);};
  return <div className="login-page"><section className="login-story"><div className="brand"><span className="brand-mark"><Icon name="sparkles" size={24}/></span><span><strong>AI Study Assistant</strong></span></div><span className="eyebrow">MỘT KHÔNG GIAN, NHIỀU CÁCH HỌC</span><h1>Hiểu bài hôm nay.<br/><em>Tự tin ngày mai.</em></h1><p>Biến tài liệu thành ý chính, câu hỏi<br/>và những điều bạn thực sự ghi nhớ.</p><StudyIllustration/><span className="login-story-footer">Được thiết kế để việc học nhẹ nhàng hơn.</span></section><section className="login-form"><span className="badge">Demo frontend · Dữ liệu mẫu</span><h2>{register?'Bắt đầu hành trình':'Chào mừng bạn trở lại'}</h2><p>{register?'Tạo hồ sơ demo trên trình duyệt này.':'Mở không gian học tập của riêng bạn.'}</p><form onSubmit={submit}>{register&&<label className="field">Tên của bạn<input className="input" name="name" placeholder="Bạn muốn AI Study Assistant gọi bạn là gì?" required maxLength={50}/></label>}<label className="field">Email demo<input className="input" name="email" type="email" placeholder="banhoc@example.com" required defaultValue="banhoc@example.com"/></label><label className="field">Mật khẩu demo<input className="input" name="password" type="password" placeholder="Ít nhất 6 ký tự" required minLength={6} defaultValue="aistudy2026" autoComplete="off"/></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="btn btn-primary" type="submit">{register?'Tạo hồ sơ demo':'Vào không gian học'}<Icon name="arrowRight" size={17}/></button></form><div className="login-divider"><span>hoặc</span></div><button className="btn btn-secondary" onClick={()=>onLogin('Bạn học','demo@aistudy.local')}><Icon name="sparkles" size={17}/>Trải nghiệm nhanh</button><p className="login-switch">{register?'Đã có hồ sơ demo?':'Lần đầu đến AI Study Assistant?'} <button onClick={()=>{setRegister(!register);setError('');}}>{register?'Đăng nhập':'Tạo hồ sơ demo'}</button></p><p className="login-disclosure">Đăng nhập mô phỏng. Mật khẩu không được lưu hoặc gửi đi.</p></section></div>;
}

function CreateLesson({onCreate,onCancel}:{onCreate:(title:string,description:string,topic:string)=>void;onCancel:()=>void}){
  const [error,setError]=useState('');
  const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget),title=String(d.get('title')||'').trim(),description=String(d.get('description')||'').trim(),topic=String(d.get('topic')||'').trim();if(title.length<3){setError('Tên bài học cần ít nhất 3 ký tự.');return;}onCreate(title,description||'Bài học mới trong thư viện của bạn.',topic||'Tự học');};
  return <div className="form-page"><button className="text-button back-button" onClick={onCancel}><Icon name="arrowLeft" size={17}/>Về thư viện</button><div className="eyebrow">TẠO ĐIỀU KIỆN CHO MỘT BUỔI HỌC TỐT</div><h1>Một bài học mới,<br/><em>một điều mới để hiểu.</em></h1><p className="muted">Đặt tên, thêm tài liệu và bắt đầu theo cách của bạn.</p><div className="create-grid"><form className="panel lesson-form" onSubmit={submit}><h2>Thông tin bài học</h2><label className="field">Tên bài học <span>*</span><input className="input" name="title" placeholder="Ví dụ: Xác suất thống kê — Chương 3" maxLength={150} required autoFocus/></label><label className="field">Chủ đề<input className="input" name="topic" placeholder="Ví dụ: Xác suất thống kê" maxLength={60}/></label><label className="field">Điều bạn muốn học<textarea className="input" name="description" rows={4} placeholder="Ghi lại mục tiêu hoặc nội dung chính của bài học…" maxLength={1000}/></label>{error&&<p className="form-error" role="alert">{error}</p>}<div className="form-actions"><button className="btn btn-secondary" type="button" onClick={onCancel}>Hủy</button><button className="btn btn-primary" type="submit">Tạo & thêm tài liệu<Icon name="arrowRight" size={17}/></button></div></form><aside className="create-help"><span className="help-orb"><Icon name="book" size={30}/></span><h3>Bắt đầu nhỏ.<br/>Học thật sâu.</h3><p>Mỗi bài học là một không gian riêng cho tài liệu, tóm tắt và công cụ ôn tập.</p><ol><li><span>01</span>Đặt tên dễ tìm lại</li><li><span>02</span>Thêm PDF, ảnh hoặc audio</li><li><span>03</span>Khám phá các công cụ học</li></ol><span className="sample-caption">Bài mới được lưu trên trình duyệt.<br/>Nội dung AI trong demo là dữ liệu mẫu.</span></aside></div></div>;
}

function UploadPanel({snapshot,onChange,lessonId,onOpen,notify}:{snapshot:DemoSnapshot;onChange:(s:DemoSnapshot)=>void;lessonId?:string;onOpen:(id:string,tab?:string)=>void;notify:(text:string)=>void}){
  const [selected,setSelected]=useState(lessonId&&snapshot.lessons.some(l=>l.id===lessonId)?lessonId:snapshot.lessons[0]?.id||'');
  const [files,setFiles]=useState<File[]>([]),[kind,setKind]=useState<'file'|'audio'|'note'>('file');
  const [note,setNote]=useState(''),[drag,setDrag]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState(false);
  const inputRef=useRef<HTMLInputElement>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null);
  const [recording,setRecording]=useState(false),[recordingPending,setRecordingPending]=useState(false),[elapsed,setElapsed]=useState(0),[audioUrl,setAudioUrl]=useState('');
  const mounted=useRef(true),requesting=useRef(false);
  const recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),recordTimer=useRef<ReturnType<typeof setInterval>|null>(null),audioUrlRef=useRef('');
  useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;if(timer.current)clearTimeout(timer.current);if(recordTimer.current)clearInterval(recordTimer.current);if(recorder.current?.state==='recording'){recorder.current.onstop=null;recorder.current.stop();}stream.current?.getTracks().forEach(t=>t.stop());if(audioUrlRef.current)URL.revokeObjectURL(audioUrlRef.current);};},[]);
  const receive=(newFiles:File[])=>{setDone(false);setError('');const allowed=newFiles.filter(f=>/\.(pdf|png|jpg|jpeg|webp|mp3|wav|m4a|webm|ogg|txt|md)$/i.test(f.name));if(allowed.length!==newFiles.length){setError('Chọn PDF, ảnh, audio, TXT hoặc Markdown.');}if(allowed.some(f=>f.size>25*1024*1024)){setError('Giới hạn demo: tối đa 25 MB cho mỗi file.');return;}setFiles(current=>[...current,...allowed].filter((f,i,a)=>a.findIndex(v=>v.name===f.name&&v.size===f.size)===i).slice(0,5));};
  const startRecording=async()=>{if(requesting.current||recording)return;setError('');if(!navigator.mediaDevices?.getUserMedia){setError('Ghi âm cần trình duyệt hỗ trợ microphone trên localhost hoặc HTTPS.');return;}requesting.current=true;setRecordingPending(true);try{const s=await navigator.mediaDevices.getUserMedia({audio:true});if(!mounted.current){s.getTracks().forEach(t=>t.stop());return;}stream.current=s;const mime=['audio/webm;codecs=opus','audio/webm','audio/mp4'].find(m=>MediaRecorder.isTypeSupported(m));const r=new MediaRecorder(s,mime?{mimeType:mime}:undefined);recorder.current=r;const chunks:BlobPart[]=[];r.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};r.onstop=()=>{const blob=new Blob(chunks,{type:r.mimeType||'audio/webm'});s.getTracks().forEach(t=>t.stop());if(audioUrlRef.current)URL.revokeObjectURL(audioUrlRef.current);audioUrlRef.current=URL.createObjectURL(blob);setAudioUrl(audioUrlRef.current);receive([new File([blob],`ghi-am-${Date.now()}.${r.mimeType.includes('mp4')?'m4a':'webm'}`,{type:r.mimeType})]);setRecording(false);};r.start();setElapsed(0);setRecording(true);recordTimer.current=setInterval(()=>setElapsed(v=>v+1),1000);}catch{stream.current?.getTracks().forEach(t=>t.stop());if(mounted.current)setError('Chưa thể truy cập microphone. Bạn có thể chọn một file ghi âm sẵn.');}finally{requesting.current=false;if(mounted.current)setRecordingPending(false);}};
  const stopRecording=()=>{if(recorder.current?.state==='recording')recorder.current.stop();if(recordTimer.current)clearInterval(recordTimer.current);setRecording(false);};
  const submit=()=>{setError('');if(!selected||!snapshot.lessons.some(l=>l.id===selected)){setError('Chọn hoặc tạo một bài học trước.');return;}if(kind==='note'&&!note.trim()){setError('Nhập ghi chú để thêm vào bài học.');return;}if(kind!=='note'&&!files.length){setError('Chọn ít nhất một tài liệu.');return;}setBusy(true);setDone(false);timer.current=setTimeout(()=>{const docs:StudyDocument[]=kind==='note'?[{id:uid('doc'),name:'Ghi chú bài học',size:new Blob([note]).size,mediaType:'text/plain',status:'ready',transcript:note.trim(),sourceMode:'demo'}]:files.map(file=>({id:uid('doc'),name:file.name,size:file.size,mediaType:file.type||'application/octet-stream',status:'ready',sourceMode:'demo'}));onChange({...snapshot,lessons:snapshot.lessons.map(l=>l.id===selected?{...l,documents:[...l.documents,...docs]}:l)});setBusy(false);setDone(true);setFiles([]);setNote('');notify('Đã thêm thông tin tài liệu vào bài học demo.');},850);};
  return <div className="upload-page"><div className="page-heading"><div><div className="eyebrow">TÀI LIỆU LÀ ĐIỂM BẮT ĐẦU</div><h1>Thêm tài liệu của bạn</h1><p>Một PDF, một ảnh chụp hoặc một ý tưởng vừa ghi lại.</p></div><span className="badge">Demo · Chưa xử lý bằng AI</span></div><div className="upload-grid"><section className="panel upload-main"><label className="field">Thêm vào bài học<select className="input" value={selected} onChange={e=>{setSelected(e.target.value);setDone(false);}} disabled={busy}><option value="" disabled>Chọn bài học</option>{snapshot.lessons.map(l=><option key={l.id} value={l.id}>{l.title}</option>)}</select></label><div className="segmented-tabs" role="group" aria-label="Loại tài liệu">{[{id:'file',label:'File tài liệu',icon:'file'},{id:'audio',label:'Ghi âm',icon:'mic'},{id:'note',label:'Ghi chú',icon:'note'}].map(t=><button key={t.id} className={kind===t.id?'active':''} disabled={busy||recording||recordingPending} onClick={()=>{setKind(t.id as typeof kind);setDone(false);setError('');}}><Icon name={t.icon} size={17}/>{t.label}</button>)}</div>
      {kind==='file'&&<button className={`dropzone ${drag?'dragging':''}`} onClick={()=>inputRef.current?.click()} onDragOver={e=>{e.preventDefault();setDrag(true);}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);receive(Array.from(e.dataTransfer.files));}} disabled={busy}><span className="upload-orb"><Icon name="upload" size={28}/></span><h3>Kéo tài liệu vào đây</h3><p>hoặc <strong>chọn file từ máy</strong></p><span>PDF, ảnh, audio, TXT/MD · tối đa 5 file, 25 MB/file</span></button>}
      <input type="file" hidden ref={inputRef} accept=".pdf,.png,.jpg,.jpeg,.webp,.mp3,.wav,.m4a,.webm,.ogg,.txt,.md" multiple onChange={e=>{receive(Array.from(e.target.files||[]));e.target.value='';}}/>
      {kind==='audio'&&<div className="recorder-panel"><span className={`record-orb ${recording?'recording':''}`}><Icon name="mic" size={27}/></span><h3>{recording?'Đang ghi âm…':'Ghi lại một ý tưởng'}</h3><div className="record-time">{String(Math.floor(elapsed/60)).padStart(2,'0')}:{String(elapsed%60).padStart(2,'0')}</div><p>Ghi âm trên trình duyệt, nghe lại rồi thêm vào bài học.</p><button className={`btn ${recording?'btn-danger':'btn-primary'}`} disabled={busy||recordingPending} onClick={recording?stopRecording:startRecording}><Icon name={recording?'stop':'mic'} size={17}/>{recordingPending?'Đang chờ microphone…':recording?'Dừng ghi âm':'Bắt đầu ghi âm'}</button><button className="text-button" disabled={busy||recording||recordingPending} onClick={()=>inputRef.current?.click()}>Chọn file ghi âm sẵn</button>{audioUrl&&<audio controls src={audioUrl}/>}<span className="sample-caption">Transcript trong demo là nội dung mẫu.</span></div>}
      {kind==='note'&&<label className="field note-upload">Nội dung ghi chú<textarea className="input" rows={10} value={note} onChange={e=>{setNote(e.target.value);setDone(false);}} placeholder="Dán nội dung bài học hoặc viết điều bạn muốn ghi nhớ…" maxLength={20000} disabled={busy}/><small>{note.length.toLocaleString('vi')} / 20.000 ký tự</small></label>}
      {kind!=='note'&&files.length>0&&<div className="selected-files">{files.map((f,i)=><div className="selected-file" key={f.name+f.size}><span className="file-symbol"><Icon name="file" size={19}/></span><div><strong>{f.name}</strong><small>{(f.size/1024/1024).toFixed(2)} MB</small></div><button className="icon-button" disabled={busy} aria-label={`Bỏ file ${f.name}`} onClick={()=>setFiles(files.filter((_,index)=>index!==i))}><Icon name="close" size={17}/></button></div>)}</div>}
      {error&&<p className="form-error" role="alert">{error}</p>}{done&&<div className="success-banner" role="status"><Icon name="check" size={20}/><div><strong>Đã lưu thông tin tài liệu</strong><span>Khám phá công cụ học với nội dung mẫu.</span></div><button className="text-button" onClick={()=>onOpen(selected)}>Mở bài học<Icon name="arrowRight" size={15}/></button></div>}
      <div className="upload-actions"><span><Icon name="info" size={15}/>File không được gửi lên máy chủ trong demo.</span><button className="btn btn-primary" onClick={submit} disabled={busy||recording||recordingPending}>{busy?<span className="spinner"/>:<Icon name="plus" size={17}/>} {busy?'Đang lưu thông tin…':'Thêm vào bài học'}</button></div>
    </section><aside className="upload-help"><h3>Một tài liệu.<br/>Nhiều cách để hiểu.</h3><p>Trong sản phẩm hoàn chỉnh, tài liệu sẽ được xử lý qua backend trước khi tạo công cụ học.</p>{[{icon:'book',title:'Nắm bắt ý chính',text:'Tóm tắt và điều cần ghi nhớ'},{icon:'sparkles',title:'Hỏi điều chưa hiểu',text:'Tutor dựa trên bài học'},{icon:'brain',title:'Kết nối kiến thức',text:'Sơ đồ tư duy dễ khám phá'},{icon:'cards',title:'Ôn tập chủ động',text:'Flashcard và Quiz'}].map(item=><div className="upload-help-item" key={item.title}><span><Icon name={item.icon} size={20}/></span><div><strong>{item.title}</strong><small>{item.text}</small></div></div>)}<div className="upload-demo-note"><Icon name="info" size={18}/><p>Bản demo hiển thị nội dung mẫu. OCR, chuyển audio thành chữ và sinh nội dung sẽ được kết nối ở giai đoạn tích hợp.</p></div></aside></div></div>;
}

function NotesPanel({snapshot,onChange,notify}:{snapshot:DemoSnapshot;onChange:(s:DemoSnapshot)=>void;notify:(s:string)=>void}){
  const [active,setActive]=useState(snapshot.notes[0]?.id||''),[title,setTitle]=useState(snapshot.notes[0]?.title||''),[content,setContent]=useState(snapshot.notes[0]?.content||''),[dirty,setDirty]=useState(false);
  const select=(n:StudyNote)=>{if(dirty&&!window.confirm('Ghi chú chưa lưu. Chuyển sang ghi chú khác?'))return;setActive(n.id);setTitle(n.title);setContent(n.content);setDirty(false);};
  const save=()=>{if(!title.trim()){notify('Đặt tên cho ghi chú trước khi lưu.');return;}const id=active||uid('note'),note={id,title:title.trim(),content,updatedAt:new Date().toISOString()};onChange({...snapshot,notes:[note,...snapshot.notes.filter(n=>n.id!==id)]});setActive(id);setDirty(false);notify('Đã lưu ghi chú trên trình duyệt.');};
  const create=()=>{if(dirty&&!window.confirm('Ghi chú chưa lưu. Tạo ghi chú mới?'))return;setActive('');setTitle('');setContent('');setDirty(false);};
  return <div className="notes-page"><div className="page-heading"><div><div className="eyebrow">LƯU LẠI ĐIỀU BẠN HIỂU</div><h1>Sổ tay học tập</h1><p>Một nơi cho những ý chính, câu hỏi và ý tưởng của bạn.</p></div><button className="btn btn-primary" onClick={create}><Icon name="plus" size={17}/>Ghi chú mới</button></div><div className="notes-grid"><aside className="panel notes-list"><h3>{snapshot.notes.length} ghi chú</h3>{snapshot.notes.map(n=><button key={n.id} className={active===n.id?'active':''} onClick={()=>select(n)}><Icon name="note" size={18}/><span><strong>{n.title}</strong><small>{n.content.slice(0,75)||'Chưa có nội dung'}</small></span></button>)}{!snapshot.notes.length&&<p className="muted">Tạo ghi chú đầu tiên để bắt đầu.</p>}</aside><section className="panel note-editor"><div className="note-editor-toolbar"><span className="muted small">{dirty?'Có thay đổi chưa lưu':'Lưu riêng trên trình duyệt'}</span><button className="btn btn-primary" onClick={save}><Icon name="check" size={17}/>Lưu ghi chú</button></div><input className="note-title" aria-label="Tên ghi chú" value={title} placeholder="Đặt tên cho ghi chú…" maxLength={150} onChange={e=>{setTitle(e.target.value);setDirty(true);}}/><textarea aria-label="Nội dung ghi chú" className="note-content" value={content} placeholder="Hôm nay bạn đã hiểu thêm điều gì?\n\nViết lại bằng lời của bạn…" onChange={e=>{setContent(e.target.value);setDirty(true);}} maxLength={30000}/><span className="sample-caption">{content.length.toLocaleString('vi')} ký tự</span></section></div></div>;
}

function ProgressPanel({snapshot,onOpen}:{snapshot:DemoSnapshot;onOpen:(id:string,tab?:string)=>void}){
  const results=Object.values(snapshot.results).flat(),total=results.length,average=total?Math.round(results.reduce((s,r)=>s+r.scorePercentage,0)/total):0,best=total?Math.max(...results.map(r=>r.scorePercentage)):0;
  return <div className="progress-page"><div className="page-heading"><div><div className="eyebrow">NHÌN LẠI ĐỂ TIẾN XA HƠN</div><h1>Từng bước đều được ghi nhận</h1><p>Theo dõi kết quả từ những phiên học trong demo.</p></div><span className="badge">Kết quả Quiz mẫu</span></div><div className="stats-row"><Stat icon="quiz" value={total.toString().padStart(2,'0')} title="Bài Quiz đã làm" sub="Qua các bài học của bạn" accent="mint"/><Stat icon="chart" value={average+'%'} title="Điểm trung bình" sub="Từ các lần nộp bài" accent="lavender"/><Stat icon="sparkles" value={best+'%'} title="Điểm tốt nhất" sub="Tiếp tục thử thách bản thân" accent="peach"/></div><section className="panel progress-lessons"><div className="section-heading"><h2>Hành trình theo bài học</h2><span className="muted small">Lưu tại trình duyệt</span></div>{snapshot.lessons.map(l=>{const r=snapshot.results[l.id]||[],reviews=Object.keys(snapshot.reviews[l.id]||{}).length;return <button className="progress-lesson-row" key={l.id} onClick={()=>onOpen(l.id,'quiz')}><span className={`stat-icon ${l.accent}`}><Icon name={accentIcon[l.accent]}/></span><div><strong>{l.title}</strong><small>{reviews} thẻ đã đánh giá · {r.length} lần làm Quiz</small></div><div className="progress-row-score"><strong>{r.length?r[r.length-1].scorePercentage+'%':'Chưa làm'}</strong><span>{r.length?'Lần gần nhất':'Bắt đầu Quiz'}</span></div><Icon name="chevronRight" size={17}/></button>;})}</section><div className="progress-note"><Icon name="info" size={18}/><p>Lịch ôn tự động và phân tích chủ đề mạnh/yếu sẽ hiển thị khi module học cung cấp dữ liệu. Demo hiện ghi nhận điểm Quiz và đánh giá flashcard.</p></div></div>;
}
