'use strict';
const $ = s => document.querySelector(s);
const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state = {token:sessionStorage.getItem('study-demo-token'),user:null,lessons:[],total:0,progress:{},health:{},view:'overview',lesson:null,tab:'documents',records:[],cards:[],quiz:null,grade:null,search:'',busy:false};
const names = {overview:'Tổng quan',lessons:'Thư viện bài học',console:'API Console',database:'Database',integrations:'Kết nối module',detail:'Chi tiết bài học'};
let toastTimer;
function toast(message) { $('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4200); }
function date(value) { return new Date(value).toLocaleDateString('vi-VN',{day:'2-digit',month:'2-digit',year:'numeric'}); }
function badge(value) { const map={ready:['Đã xử lý','green'],pending:['Chờ xử lý','amber'],processing:['Đang xử lý','amber'],failed:['Thất bại','red']};const item=map[value]||[value,''];return `<span class="tag ${item[1]}">${escape(item[0])}</span>`; }
function mockNote() { return '<div class="mock-banner">◌ &nbsp; Chế độ mô phỏng · Nội dung OOP mẫu dùng để kiểm tra kết nối và lưu dữ liệu. Module của đồng đội sẽ cung cấp kết quả thật.</div>'; }
async function api(path,options={}) {
 const headers={...(options.body && !(options.body instanceof FormData)?{'Content-Type':'application/json'}:{}),...(state.token?{Authorization:`Bearer ${state.token}`} :{}),...options.headers};
 const start=performance.now();let response;let data;
 try { response=await fetch(path,{...options,headers});const text=await response.text();try{data=text?JSON.parse(text):null;}catch{data=text;} }
 catch(error){throw new Error('Không kết nối được backend. Kiểm tra server và thử lại.');}
 const record={key:crypto.randomUUID(),method:options.method||'GET',path,status:response.status,ms:Math.round(performance.now()-start),data,requestId:response.headers.get('X-Request-ID')};state.records.unshift(record);state.records=state.records.slice(0,30);
 if(!response.ok) { const error=new Error(data?.error?.message||`HTTP ${response.status}`);error.code=data?.error?.code;error.data=data;throw error; }
 return data;
}
const post=(path,data)=>api(path,{method:'POST',body:JSON.stringify(data)});
function heading(title,subtitle,actions='') { return `<div class="page-heading"><div><span class="eyebrow">AI STUDY ASSISTANT / BACKEND</span><h1>${escape(title)}</h1><p>${escape(subtitle)}</p></div><div class="heading-actions">${actions}</div></div>`; }
function empty(message) { return `<div class="empty"><span class="empty-icon">◇</span>${escape(message)}</div>`; }
function activity() { return `<section class="panel activity-panel"><div class="panel-header"><div><h2>Hoạt động API</h2><small>Các request thực tế từ phiên demo hiện tại</small></div><span class="request-count">${state.records.length} request gần nhất</span></div><div class="table-wrap"><table><thead><tr><th>PHƯƠNG THỨC</th><th>ENDPOINT</th><th>TRẠNG THÁI</th><th>THỜI GIAN</th></tr></thead><tbody>${state.records.slice(0,5).map(r=>`<tr class="activity-row" data-record="${r.key}"><td><span class="method ${r.method.toLowerCase()}">${r.method}</span></td><td class="route">${escape(r.path)}</td><td>${badge(String(r.status))}</td><td>${r.ms} ms</td></tr>`).join('')}</tbody></table></div></section>`; }
function metrics() { const documents=state.lessons.reduce((a,l)=>a+l.document_count,0);return `<div class="metrics">${[
 ['Bài học của bạn',state.total,'▤','Đã lưu trong SQLite'],['Tài liệu đã tải',documents,'▧','Trong các bài học đang hiển thị'],['Lần luyện tập',state.progress.attempts||0,'◷','Bài làm đã được lưu'],['Điểm trung bình',`${state.progress.average_score||0}%`,'↗','Kết quả quiz mô phỏng']
 ].map(([label,value,icon,foot])=>`<div class="metric"><div class="metric-top"><span>${label}</span><span class="metric-icon">${icon}</span></div><div class="metric-number">${value}</div><div class="metric-foot">${foot}</div></div>`).join('')}</div>`; }
function overview() { return `${heading('Một nơi cho mọi kiến thức.','Không gian kiểm tra backend của bạn đã sẵn sàng.', '<button class="button" data-new-lesson>＋ Tạo bài học</button>')}
 <section class="hero"><div><span class="eyebrow">TỪ TÀI LIỆU ĐẾN KIẾN THỨC</span><h2>Ghi lại một lần.<br>Hiểu bài cả kỳ.</h2><p>API rõ ràng, dữ liệu bền vững và các module cùng kết nối.<br>Bắt đầu với một bài học, khám phá toàn bộ luồng demo.</p><div class="hero-pills"><span>FastAPI</span><span>SQLite · WAL</span><span>Phạm vi: Người 2</span></div></div><div class="architecture" aria-hidden="true"><div class="core-box"><b>▥</b><span>BACKEND</span></div><div class="satellite s1"><span>◇</span>AI Tutor</div><div class="satellite s2"><span>▧</span>Tài liệu</div><div class="satellite s3"><span>✦</span>Luyện tập</div></div></section>
 ${metrics()}<div class="main-grid"><section class="panel"><div class="panel-header"><div><h2>Thư viện gần đây</h2><small>Tiếp tục từ nơi bạn đã dừng lại</small></div><button class="text-button" data-view="lessons">Xem tất cả ↗</button></div><div class="lesson-list">${state.lessons.slice(0,4).map(l=>`<div class="lesson-row" role="button" tabindex="0" data-lesson="${l.id}"><div class="lesson-icon">▤</div><div class="lesson-info"><strong>${escape(l.title)}</strong><small>${l.document_count} tài liệu · ${date(l.created_at)}</small></div><span class="tag ${l.document_count?'green':''}">${l.document_count?'Có tài liệu':'Mới tạo'}</span><span class="row-arrow">↗</span></div>`).join('')||empty('Tạo bài học đầu tiên để bắt đầu.')}</div></section>
 <section class="panel"><div class="panel-header"><div><h2>Luồng kết nối</h2><small>Mỗi module, một phần việc rõ ràng</small></div><span class="tag green">API đang chạy</span></div><div class="pipeline">${[['▧','Nhận tài liệu','Upload · kiểm tra · lưu file','Thật'],['◇','Xử lý đầu vào','PDF / OCR / Audio · Người 4','Mô phỏng'],['✦','AI & ngữ cảnh','Summary / Tutor / RAG · Người 3','Mô phỏng'],['▥','Lưu & truy xuất','SQLite / API · Người 2','Thật']].map(([icon,title,desc,status])=>`<div class="pipeline-step"><div class="step-icon">${icon}</div><div class="step-label"><strong>${title}</strong><small>${desc}</small></div><span class="step-state ${status==='Mô phỏng'?'mock':''}">${status}</span></div>`).join('')}</div><div class="section-note">Các kết quả học mẫu có nhãn <b>demo</b>. Dữ liệu được lưu thật vào database riêng của bản demo.</div></section></div>${activity()}`; }
function library() { return `${heading('Thư viện bài học','Quản lý bài học và dữ liệu của tài khoản hiện tại.','<button class="button" data-new-lesson>＋ Tạo bài học</button>')}<form class="search" id="search-form"><input name="query" placeholder="Tìm bài học…" value="${escape(state.search)}" aria-label="Tìm bài học"><button class="button secondary">Tìm kiếm</button></form><div class="library-grid">${state.lessons.map(l=>`<article class="panel lesson-card" role="button" tabindex="0" data-lesson="${l.id}"><div class="lesson-icon">▤</div><h3>${escape(l.title)}</h3><p>${escape(l.description||'Chưa có mô tả.')}</p><div class="card-bottom"><span>${l.document_count} tài liệu · ${l.chat_count} hội thoại</span><span>↗</span></div></article>`).join('')||empty('Không tìm thấy bài học. Bạn có thể tạo bài học mới.')}</div>`; }
function detailShell(body) { const l=state.lesson;return `<button class="back-link" data-view="lessons">← Quay lại thư viện</button>${heading(l.title,l.description||'Bài học của bạn', '<button class="button secondary small" data-edit-lesson>Chỉnh sửa</button><button class="button danger small" data-delete-lesson>Xóa bài học</button>')}<div class="tabs" role="tablist">${[['documents','Tài liệu'],['summary','Tóm tắt'],['chat','AI Tutor'],['flashcards','Flashcard'],['quiz','Quiz'],['progress','Tiến độ']].map(([id,label])=>`<button class="tab ${state.tab===id?'active':''}" role="tab" aria-selected="${state.tab===id}" data-tab="${id}">${label}</button>`).join('')}</div><section class="panel detail-content">${body}</section>`; }
function documentsView() { return `<div class="content-pad"><div class="upload-area"><strong>Thêm tài liệu cho bài học</strong><p>PDF · Ảnh · Audio · TXT / Markdown UTF-8 · Tối đa 20 MB<br>Ở chế độ demo, PDF/ảnh/audio nhận nội dung mẫu, chưa được trích xuất thật.</p><form id="upload-form"><div class="upload-actions"><input type="file" name="file" required accept=".pdf,.txt,.md,.png,.jpg,.jpeg,.webp,.mp3,.wav,.m4a,.ogg" aria-label="Chọn tài liệu"><button class="button" type="submit">Upload ↗</button></div></form><button class="text-button" data-upload-sample style="margin-top:12px">Hoặc thử với tài liệu Markdown mẫu ↗</button></div>${state.lesson.documents.map(d=>`<div class="lesson-row"><div class="lesson-icon">▧</div><div class="lesson-info"><strong>${escape(d.filename)}</strong><small>${(d.size_bytes/1024).toFixed(1)} KB · ${date(d.created_at)} · ${escape(d.source_mode)}</small>${d.error_code?`<small class="danger-text">${escape(d.error_code)}</small>`:''}</div>${badge(d.status)}<button class="text-button" data-document="${d.id}">Xem</button><button class="text-button" data-download="${d.id}">Tải</button>${d.status==='failed'?`<button class="text-button" data-retry="${d.id}">Thử lại</button>`:''}<button class="text-button danger-text" data-delete-document="${d.id}">Xóa</button></div>`).join('')||empty('Chưa có tài liệu. Upload để bắt đầu.')}</div>`; }
async function renderTab() {
 const id=state.lesson.id;let body='';
 if(state.tab==='documents') body=documentsView();
 if(state.tab==='summary') {
  let summary=null;try{summary=await api(`/summary/${id}`);}catch(e){if(e.code!=='SUMMARY_NOT_FOUND')throw e;}
  body=`<div class="content-pad"><div class="action-header"><h2>Tóm tắt bài học</h2><button class="button small" data-generate="summary">${summary?'Tạo lại':'Tạo tóm tắt'} ↗</button></div>${mockNote()}${summary?`<p class="summary-body">${escape(summary.summary)}</p><div class="keypoints">${summary.key_points.map(p=>`<div class="keypoint"><span>✦</span>${escape(p)}</div>`).join('')}</div><p class="hint" style="margin-top:20px">Đã lưu · ${date(summary.updated_at)} · ${escape(summary.source_mode)}</p>`:empty('Chưa có tóm tắt. Tạo tóm tắt sau khi tài liệu đã xử lý.')}</div>`;
 }
 if(state.tab==='chat') {
  const history=await api(`/chat/${id}?limit=100`);
  body=`<div class="content-pad"><div class="action-header"><h2>AI Tutor</h2><span class="tag amber">Mô phỏng</span></div>${mockNote()}<div class="chat-history">${history.items.map(c=>`<div class="chat-question">${escape(c.question)}</div><div class="chat-answer">${escape(c.answer)}<small>Đã lưu · ${escape(c.source_mode)} · ${c.sources.length} nguồn</small></div>`).join('')||empty('Đặt câu hỏi để thử API và lưu lịch sử hội thoại.')}</div><form class="chat-form" id="chat-form"><input name="question" placeholder="Ví dụ: Giải thích đa hình bằng ví dụ đơn giản…" required maxlength="4000" aria-label="Câu hỏi"><button class="button">Gửi ↗</button></form></div>`;
 }
 if(state.tab==='flashcards') {
  state.cards=(await api(`/flashcards/${id}`)).items;
  body=`<div class="content-pad"><div class="action-header"><h2>Thẻ ghi nhớ</h2><button class="button small" data-generate="flashcards">${state.cards.length?'Tạo lại bộ thẻ':'Tạo flashcard'} ↗</button></div>${mockNote()}<p class="hint" style="margin-bottom:17px">Mở đáp án rồi đánh giá mức độ nhớ. Tạo lại bộ thẻ sẽ thay thế bộ hiện tại và lịch sử đánh giá của bộ đó.</p><div class="flash-grid">${state.cards.map((c,i)=>`<article class="flashcard"><span class="eyebrow">THẺ ${String(i+1).padStart(2,'0')} · ${escape(c.difficulty)}</span><h3>${escape(c.question)}</h3><details><summary>Xem đáp án</summary><p>${escape(c.answer)}</p></details><div class="ratings">${[['again','Học lại'],['hard','Khó'],['good','Nhớ'],['easy','Dễ']].map(([rating,label])=>`<button data-review="${c.id}" data-rating="${rating}">${label}</button>`).join('')}</div></article>`).join('')||empty('Chưa có flashcard. Tạo bộ thẻ để thử chức năng.')}</div></div>`;
 }
 if(state.tab==='quiz') {
  state.quiz=null;try{state.quiz=await api(`/quiz/${id}`);}catch(e){if(e.code!=='QUIZ_NOT_FOUND')throw e;}
  const quiz=state.quiz;
  body=`<div class="content-pad"><div class="action-header"><h2>Kiểm tra kiến thức</h2><button class="button small" data-generate="quiz">Tạo quiz mới ↗</button></div>${mockNote()}${quiz?`<form id="quiz-form">${quiz.questions.map((q,i)=>`<div class="quiz-question"><h3>${i+1}. ${escape(q.question)}</h3>${q.options.map((o,j)=>`<label class="quiz-option"><input type="radio" name="${escape(q.id)}" value="${escape(o)}" required><span>${String.fromCharCode(65+j)}. ${escape(o)}</span></label>`).join('')}</div>`).join('')}<button class="button">Nộp bài & lưu kết quả ↗</button></form><div id="quiz-grade">${gradeHtml()}</div>`:empty('Chưa có quiz. Tạo quiz sau khi tài liệu đã xử lý.')}</div>`;
 }
 if(state.tab==='progress') {
  const p=await api(`/progress/${id}`);
  body=`<div class="content-pad"><div class="action-header"><h2>Tiến độ bài học</h2><span class="tag">Dữ liệu đã lưu</span></div><div class="metrics">${[['Lần làm quiz',p.attempts],['Điểm trung bình',p.average_score+'%'],['Điểm cao nhất',p.best_score+'%'],['Lượt ôn thẻ',p.flashcard_reviews]].map(([name,value])=>`<div class="metric"><div class="metric-top">${name}</div><div class="metric-number">${value}</div></div>`).join('')}</div><h3>Lịch sử luyện tập</h3><div class="table-wrap"><table style="margin-top:17px"><thead><tr><th>NGÀY</th><th>SỐ CÂU ĐÚNG</th><th>ĐIỂM</th><th>CHẾ ĐỘ</th></tr></thead><tbody>${p.recent_attempts.map(a=>`<tr><td>${date(a.created_at)}</td><td>${a.correct}/${a.total}</td><td>${a.score}%</td><td>${escape(a.source_mode)}</td></tr>`).join('')}</tbody></table></div>${!p.attempts?empty('Chưa có bài làm. Thử quiz để xem tiến độ.'):''}<div class="storage-note">Backend lưu điểm và số câu đúng. Phân tích chủ đề mạnh/yếu, lộ trình ôn tập và nhắc nhở thuộc module của Người 5.</div></div>`;
 }
 $('#main').innerHTML=detailShell(body);
 const history=$('.chat-history');if(history) history.scrollTop=history.scrollHeight;
}
function gradeHtml() { if(!state.grade)return '';const g=state.grade;return `<div class="quiz-result"><strong>${g.score}%</strong><p>${g.correct}/${g.total} câu đúng · Kết quả đã được lưu · Mô phỏng</p>${g.feedback.map(f=>`<p>${f.correct?'✓':'○'} ${escape(f.question_id)} · ${escape(f.explanation)}</p>`).join('')}</div>`; }
function consoleView() { return `${heading('API Console','Gửi request thật và xem phản hồi trực tiếp từ backend.')}<div class="console-grid"><section class="panel content-pad"><h2>Thử một endpoint</h2><form id="console-form" class="console-form"><label>Endpoint<select name="endpoint" id="endpoint-select"><option value="GET /health">GET /health</option><option value="GET /lessons">GET /lessons</option><option value="GET /auth/me">GET /auth/me</option><option value="GET /progress">GET /progress</option><option value="POST /lessons">POST /lessons</option></select></label><label>JSON body<textarea name="body" spellcheck="false">{"title": "Bài học từ API Console", "description": "Dữ liệu được lưu thật"}</textarea></label><p class="hint">Bearer token được gửi từ phiên demo hiện tại. Token không xuất hiện trong nhật ký hiển thị.</p><button class="button" style="margin-top:19px">Gửi request ↗</button></form></section><section class="code-panel"><div class="code-header"><span>RESPONSE · application/json</span><span id="console-status" class="response-chip">Sẵn sàng</span></div><pre id="console-output">Chọn endpoint và gửi request để xem kết quả.</pre></section></div>${activity()}`; }
function databaseView() { const tables=[['users','id · name · email','password_hash · created_at'],['sessions','token_hash → user_id','expires_at · created_at'],['lessons','id → user_id','title · description · timestamps'],['documents','id → lesson_id','filename · content · status · hash'],['transcripts','id → lesson_id / document_id','content · created_at'],['summaries','lesson_id · summary','key_points · source_mode'],['chats','id → lesson_id','question · answer · sources'],['flashcards','id → lesson_id','question · answer · difficulty'],['flashcard_reviews','id → flashcard_id / user_id','rating · created_at'],['quizzes','id → lesson_id','questions · source_mode'],['quiz_attempts','id → quiz_id / user_id','answers · score · feedback'],['schema_migrations','version','Lịch sử cập nhật cấu trúc']];return `${heading('Database được tổ chức rõ ràng.','Sơ đồ bảng của backend · Không hiển thị mật khẩu, token hoặc nội dung nhạy cảm.')}<div class="database-grid">${tables.map(([name,...fields])=>`<section class="panel schema-card"><h3>▥ ${name}</h3>${fields.map(f=>`<p>${escape(f)}</p>`).join('')}</section>`).join('')}</div><div class="storage-note"><b>SQLite · Khóa ngoại · WAL · Transaction · Migration</b><br>Dữ liệu demo ở backend/data/demo/. Mỗi thành viên dùng database local riêng. Không commit database, file upload hoặc .env vào Git. Sơ đồ này mô tả cấu trúc; truy xuất dữ liệu thật qua API có xác thực.</div>`; }
function integrationsView() { return `${heading('Các module cùng kết nối.','Ranh giới rõ ràng giúp 5 thành viên làm việc song song.')}<section class="panel">${[['▥','Backend / Database','Người 2 · API, tài khoản, lưu trữ, quyền truy cập','Hoạt động thật','green'],['◇','AI / Smart Context','Người 3 · Summary, AI Tutor, prompt và RAG','Mô phỏng','amber'],['▧','File Processing','Người 4 · PDF, OCR/Vision, Audio → text','Mô phỏng','amber'],['✦','Learning / Testing','Người 5 · Sinh flashcard, quiz và chấm bài','Mô phỏng','amber'],['▤','Frontend / UI','Người 1 · Giao diện sản phẩm và gọi API','Tách biệt','']].map(([icon,title,desc,status,color])=>`<div class="connection-row"><div class="step-icon">${icon}</div><div class="step-label"><strong>${title}</strong><small>${desc}</small></div><span class="tag ${color}">${status}</span></div>`).join('')}</section><div class="ownership-grid"><section class="panel ownership-card"><h3>Kết nối qua provider</h3><p>Backend định nghĩa input/output. Đồng đội cung cấp class riêng, cấu hình đường dẫn module trong .env. Chỉ backend ghi database.</p></section><section class="panel ownership-card"><h3>Chế độ chạy thật</h3><p>APP_MODE=production tắt trang demo và tài khoản mẫu. Module chưa kết nối trả lỗi rõ ràng; không tự dùng dữ liệu mô phỏng.</p></section></div>`; }
async function refresh() { const [lessons,progress,health]=await Promise.all([api(`/lessons?limit=100&q=${encodeURIComponent(state.search)}`),api('/progress'),api('/health')]);state.lessons=lessons.items;state.total=lessons.total;state.progress=progress;state.health=health; }
async function render() { $('#page-name').textContent=names[state.view]||names.detail;document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===state.view||(state.view==='detail'&&n.dataset.view==='lessons')));$('#main').setAttribute('aria-busy','false');if(state.view==='detail')return renderTab();const views={overview,lessons:library,console:consoleView,database:databaseView,integrations:integrationsView};$('#main').innerHTML=views[state.view](); }
async function navigate(view) { state.view=view;if(['overview','lessons'].includes(view))await refresh();await render(); }
async function openLesson(id) { state.lesson=await api(`/lessons/${id}`);state.view='detail';state.tab='documents';state.grade=null;await render(); }
async function action(button,fn) { if(state.busy)return;state.busy=true;const old=button?.innerHTML;if(button){button.disabled=true;button.setAttribute('aria-busy','true');if(button.classList.contains('button'))button.textContent='Đang xử lý…';}try{await fn();}catch(error){toast(error.message);}finally{state.busy=false;if(button&&button.isConnected){button.disabled=false;button.removeAttribute('aria-busy');button.innerHTML=old;}} }
async function start() { try { const health=await api('/health');if(health.mode!=='demo')throw new Error('Trang này chỉ hoạt động ở chế độ demo.');let user;if(state.token){try{user=await api('/auth/me');}catch{state.token=null;sessionStorage.removeItem('study-demo-token');}}if(!user){const session=await post('/auth/login',{email:'demo@studyassistant.dev',password:'DemoStudy!2026'});state.token=session.access_token;sessionStorage.setItem('study-demo-token',state.token);user=session.user;}state.user=user;$('#user-name').textContent=user.name;$('#api-status').innerHTML='<i></i>API đang chạy';await refresh();await render();}catch(error){$('#api-status').textContent='Chưa kết nối';$('#main').innerHTML=heading('Chưa kết nối được backend',error.message,'<button class="button" data-reconnect>Thử lại ↻</button>');} }
document.addEventListener('click',async event=>{
 const b=event.target.closest('button,[data-lesson],[data-record]');if(!b)return;
 if(b.dataset.view)return action(b,()=>navigate(b.dataset.view));
 if(b.hasAttribute('data-new-lesson')) { $('#lesson-form').reset();$('#lesson-dialog').showModal();return; }
 if(b.hasAttribute('data-close-dialog')) { $('#lesson-dialog').close();return; }
 if(b.dataset.lesson)return action(b,()=>openLesson(b.dataset.lesson));
 if(b.dataset.tab)return action(b,async()=>{state.tab=b.dataset.tab;state.grade=null;await render();});
 if(b.dataset.generate)return action(b,async()=>{if(b.dataset.generate==='flashcards'&&state.cards.length&&!confirm('Tạo lại sẽ thay thế bộ thẻ và lịch sử đánh giá hiện tại. Tiếp tục?'))return;await post(`/${b.dataset.generate}/${state.lesson.id}/generate`);state.grade=null;await renderTab();toast('Đã tạo và lưu dữ liệu mô phỏng.');});
 if(b.hasAttribute('data-upload-sample'))return action(b,async()=>{const form=new FormData();form.append('lesson_id',state.lesson.id);form.append('file',new Blob(['# OOP\nClass là bản thiết kế. Object là thể hiện của class.\nĐa hình: cùng giao diện, nhiều cách thực thi.\n'],{type:'text/markdown'}),'study-notes.md');const d=await api('/upload',{method:'POST',body:form});await waitDocument(d.id);state.lesson=await api(`/lessons/${state.lesson.id}`);await renderTab();toast('Đã upload và lưu tài liệu mẫu.');});
 if(b.dataset.document)return action(b,async()=>{const d=await api(`/documents/${b.dataset.document}`);const dialog=document.createElement('dialog');dialog.innerHTML=`<div class="dialog-head"><h2>${escape(d.filename)}</h2><button class="icon-button" aria-label="Đóng">×</button></div>${badge(d.status)}<pre class="document-text">${escape(d.content||'Chưa có nội dung đã xử lý.')}</pre>`;document.body.append(dialog);dialog.querySelector('button').onclick=()=>{dialog.close();dialog.remove();};dialog.showModal();});
 if(b.dataset.download)return action(b,async()=>{const response=await fetch(`/documents/${b.dataset.download}/download`,{headers:{Authorization:`Bearer ${state.token}`}});if(!response.ok)throw new Error('Không tải được file.');const blob=await response.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=state.lesson.documents.find(d=>d.id===b.dataset.download)?.filename||'document';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 if(b.dataset.retry)return action(b,async()=>{await post(`/documents/${b.dataset.retry}/retry`);await waitDocument(b.dataset.retry);state.lesson=await api(`/lessons/${state.lesson.id}`);await renderTab();});
 if(b.dataset.deleteDocument)return action(b,async()=>{if(!confirm('Xóa tài liệu và file đã lưu?'))return;await api(`/documents/${b.dataset.deleteDocument}`,{method:'DELETE'});state.lesson=await api(`/lessons/${state.lesson.id}`);await renderTab();toast('Đã xóa tài liệu.');});
 if(b.hasAttribute('data-delete-lesson'))return action(b,async()=>{if(!confirm('Xóa bài học cùng tài liệu, hội thoại và kết quả học liên quan?'))return;await api(`/lessons/${state.lesson.id}`,{method:'DELETE'});await navigate('lessons');toast('Đã xóa bài học.');});
 if(b.hasAttribute('data-edit-lesson'))return action(b,async()=>{const title=prompt('Tên bài học mới:',state.lesson.title);if(title===null)return;state.lesson=await api(`/lessons/${state.lesson.id}`,{method:'PATCH',body:JSON.stringify({title})});await render();toast('Đã cập nhật bài học.');});
 if(b.dataset.review)return action(b,async()=>{await post(`/flashcards/${b.dataset.review}/review`,{rating:b.dataset.rating});toast('Đã lưu đánh giá thẻ.');});
 if(b.dataset.record!==undefined) { const r=state.records.find(record=>record.key===b.dataset.record);if(!r)return;state.view='console';await render();$('#console-output').textContent=JSON.stringify(r.data,null,2);$('#console-status').textContent=`${r.status} · ${r.ms} ms`;return; }
 if(b.id==='reconnect'||b.hasAttribute('data-reconnect'))return action(b,start);
});
document.addEventListener('keydown',event=>{if((event.key==='Enter'||event.key===' ')&&event.target.matches('[data-lesson]')){event.preventDefault();event.target.click();}});
async function waitDocument(id) { for(let i=0;i<40;i++){const d=await api(`/documents/${id}`);if(d.status==='ready')return d;if(d.status==='failed')throw new Error(`Xử lý thất bại: ${d.error_code}`);await new Promise(r=>setTimeout(r,250));}throw new Error('File vẫn đang xử lý. Mở lại bài học để cập nhật trạng thái.'); }
document.addEventListener('submit',event=>{
 const form=event.target;if(!['lesson-form','search-form','upload-form','chat-form','quiz-form','console-form'].includes(form.id))return;event.preventDefault();const button=form.querySelector('button[type=submit],button:not([type])');const values=new FormData(form);
 action(button,async()=>{
  if(form.id==='lesson-form'){const lesson=await post('/lessons',{title:values.get('title'),description:values.get('description')});$('#lesson-dialog').close();await refresh();await openLesson(lesson.id);toast('Đã tạo bài học.');}
  if(form.id==='search-form'){state.search=values.get('query').trim();await refresh();await render();}
  if(form.id==='upload-form'){values.append('lesson_id',state.lesson.id);const d=await api('/upload',{method:'POST',body:values});await waitDocument(d.id);state.lesson=await api(`/lessons/${state.lesson.id}`);await renderTab();toast('Đã upload và lưu tài liệu.');}
  if(form.id==='chat-form'){await post('/chat',{lesson_id:state.lesson.id,question:values.get('question')});await renderTab();toast('Đã lưu hội thoại.');}
  if(form.id==='quiz-form'){state.grade=await post(`/quizzes/${state.quiz.id}/submit`,{answers:Object.fromEntries(values.entries())});$('#quiz-grade').innerHTML=gradeHtml();$('#quiz-grade').scrollIntoView({behavior:'smooth',block:'nearest'});toast('Đã lưu kết quả bài làm.');}
  if(form.id==='console-form'){const [method,path]=values.get('endpoint').split(' ');let body;if(method==='POST'){body=JSON.stringify(JSON.parse(values.get('body')));}try{const data=await api(path,{method,...(body?{body}:{})});$('#console-output').textContent=JSON.stringify(data,null,2);}catch(error){$('#console-output').textContent=JSON.stringify(error.data||{error:error.message},null,2);}const r=state.records[0];$('#console-status').textContent=`${r.status} · ${r.ms} ms`;$('.activity-panel').outerHTML=activity();}
 });
});
start();
